{% set name = "vcrpy" %}
{% set version = "6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 88e13d9111846745898411dbc74a75ce85870af96dd320d75f1ee33158addc09

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip

  run:
    - python >=3.8
    - pyyaml
    - wrapt
    - yarl

test:
  # Python imports
  imports:
    - vcr
    - vcr.persisters
    - vcr.serializers
    - vcr.stubs

about:
  home: https://github.com/kevin1024/vcrpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Automatically mock your HTTP interactions to simplify and speed up testing
  dev_url: https://github.com/kevin1024/vcrpy
  doc_url: https://vcrpy.readthedocs.io/

extra:
  recipe-maintainers:
    - dopplershift
