{% set name = "vcrpy" %}
{% set version = "8.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e585ca3cd9bb751e402728a00394847561250588eebc047b4d3c8948d5487733

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip

  run:
    - python >={{ python_min }}
    - pyyaml
    - wrapt
    - yarl

test:
  requires:
    - python {{ python_min }}
  imports:
    - vcr
    - vcr.persisters
    - vcr.serializers
    - vcr.stubs

about:
  home: https://github.com/kevin1024/vcrpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Automatically mock your HTTP interactions to simplify and speed up testing
  dev_url: https://github.com/kevin1024/vcrpy
  doc_url: https://vcrpy.readthedocs.io/

extra:
  recipe-maintainers:
    - dopplershift
