{% set name = "vcrpy" %}
{% set version = "4.0.2" %}
{% set sha256 = "9740c5b1b63626ec55cefb415259a2c77ce00751e97b0f7f214037baaf13c7bf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  number: 0

requirements:
  host:
    - python
    - setuptools
    - pip

  run:
    - python
    - pyyaml
    - wrapt
    - six >=1.5
    - mock  # [py27]
    - contextlib2  # [py27]

test:
  # Python imports
  imports:
    - vcr
    - vcr.persisters
    - vcr.serializers
    - vcr.stubs

about:
  home: https://github.com/kevin1024/vcrpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Automatically mock your HTTP interactions to simplify and speed up testing'
  dev_url: https://github.com/kevin1024/vcrpy
  doc_url: https://vcrpy.readthedocs.io/

extra:
  recipe-maintainers:
    - dopplershift
