appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Df48sDohAPWM+Ox0s3hf5GD+K/bDU877vU0rReO5xWd5moqIEjMNthWBdXUnx2sZX/jr16Xz9St1Cob7xt8GFJ+3HUWSb1ZOUlOdqd4xzQeCP74zxJTRXZt85Kjr6i5dRFC2H+SCKByRR1BcqrceQBnSg2PzCMEiQsc2O+zXjEZKNiIlT2/6yZ9UJm+RbJkQUgg4C8RLy7WvP57DHzz9YleW4uygTzzUp1dKTRMNzE6gEVt3Z85UxsC+hihxyJ33WhmiRcQ5zRUIqsRWq+WuVETP4+eRBBC4+IZBPzXnIxfOvLRcBfNvk2Y2Xo62z9KkAt2H1exobpuPj9Ux0cSwBqm/F1GrqGoITMMAG3GoHK3a1d0fM6CcwJoJTkn7nWPwdDGeLVdugjDDi9Jx/dU+G7w9wzUhKR5RTMFQi3sJCf0i4tuxer4Hom/gNJNzjCsescnK79acD/uXwQ8ECaeyaFwnd4oo+IIlYhP9Ixi0/nmKor6CD47mX0XP8OONMaqfXim+kui9zjbxLj9Hamc9561M7geqj73SZZ34kbR0jU8Agjiqw+SLKJoCRzcg4ywIjjfADV9pSfH6A+vGbd7SOltUT/P/pNxFOReqScaqS+0oMggufJNv+nPZzvf95c8g640Y3mh35wF8BuoIfqNZ2gTHrxjk1s/eDDYx0If1K3w=}
provider:
  win: azure
conda_forge_output_validation: false
